# load the base image
FROM node:17-alpine

WORKDIR /app

COPY package.json ./

# Install required packages
RUN npm install --legacy-peer-deps

# Copy all the remaining files
COPY . .

EXPOSE 3000

# Run the application
CMD ["npm", "start"]